// Generated by RamdaScript 0.2.1

;(function () {

window.app = {
    ENTER_KEY : 13,
    ESCAPE_KEY : 27,
    dom : R.pick([
            'ul',
            'label',
            'button',
            'input',
            'li',
            'div',
            'header',
            'footer',
            'span',
            'strong',
            'h1',
            'section',
            'a'
        ], React.DOM)
}

})()