// Generated by RamdaScript 0.2.1

;(function () {

var refresh = function () {
    return R.call(
        R.pipe(
            R.slice(1, Infinity), 
            R.when(
                R.anyPass([
                        R.equals(''),
                        R.equals('active'),
                        R.equals('completed')
                    ]), 
                app.stateSet('filter'))), location.hash)
}

window.addEventListener.bind(window)('hashchange', refresh)

})()