// Generated by RamdaScript 0.2.1

;(function () {

var namespace = 'todos-ramdascript'

var get = function () {
    return JSON.parse(
        R.call(
            R.defaultTo(null), 
            localStorage.getItem(namespace)))
}

var save = R.curry(function (data) {
    return R.call(
        R.unless(
            R.isEmpty(), 
            function () {
                return localStorage.setItem(namespace, 
                    JSON.stringify(data))
            }), data)
})

app.storage = {
    get : get,
    save : save
}

})()