// Generated by RamdaScript 0.2.1

;(function () {

var d = app.dom

var Footer = function () {
    return d.footer({
            className : 'footer'
        }, [
            d.span({
                    className : 'todo-count'
                }, 
                d.strong({}, 
                    getItemsLeft())),
            d.ul({
                    className : 'filters'
                }, [
                    d.li({}, 
                        d.a({
                                href : '#',
                                className : selectedCls('')
                            }, 'All')),
                    d.li({}, 
                        d.a({
                                href : '#active',
                                className : selectedCls('active')
                            }, 'Active')),
                    d.li({}, 
                        d.a({
                                href : '#completed',
                                className : selectedCls('completed')
                            }, 'Completed'))
                ]),
            d.button({
                    className : 'clear-completed',
                    onClick : app.destroyCompleted
                }, 'Clear completed')
        ])
}

var selectedCls = R.curry(function (f) {
    return R.call(
        R.ifElse(
            R.equals(
                app.stateGet('filter')), 
            R.always('selected'), 
            R.always('')), f)
})

var getItemsLeft = function () {
    return R.call(
        R.pipe(
            R.reduce(
                R.curry(function (a, x) {
                    return R.call(
                        R.ifElse(
                            R.propEq('completed', false), 
                            function () {
                                return R.inc(a)
                            }, 
                            R.always(a)), x)
                }), 0), R.toString, 
            R.cond([
                    [
                        R.equals('1'),
                        R.concat(R.__, ' item left')
                    ],
                    [
                        R.T,
                        R.concat(R.__, ' items left')
                    ]
                ])), 
        app.stateGet('todos'))
}

app.Footer = Footer

})()