// Generated by RamdaScript 0.2.1

;(function () {

var d = app.dom

var Main = R.curry(function (todos) {
    return d.section({
            className : 'todoapp'
        }, [
            d.header({
                    className : 'header'
                }, [
                    d.h1({}, 'todos'),
                    d.input({
                            value : app.stateGet('title'),
                            className : 'new-todo',
                            placeholder : 'What needs to be done?',
                            onChange : handleChange,
                            onKeyDown : handleKeydown
                        })
                ]),
            d.section({
                    className : mainCls()
                }, [
                    d.input({
                            className : 'toggle-all',
                            type : 'checkbox',
                            onClick : handleToggleAll
                        }),
                    d.ul({
                            className : 'todo-list'
                        }, 
                        R.map(app.Item, 
                            app.getTodos()))
                ]),
            getFooter(todos)
        ])
})

var mainCls = function () {
    return R.call(
        R.ifElse(
            R.pipe(app.stateGet, R.length, R.not), 
            R.always('main hidden'), 
            R.always('main')), 'todos')
}

var getFooter = R.when(
    R.pipe(R.length, 
        R.lt(0)), app.Footer)

var handleKeydown = R.when(
    R.both(
        R.propEq('keyCode', app.ENTER_KEY), 
        function () {
            return R.not(
                R.isEmpty(
                    app.stateGet('title')))
        }), 
    function () {
        return app.addTodo(
            app.stateGet('title'))
    })

var handleToggleAll = R.pipe(
    R.path([
            'target',
            'checked'
        ]), app.toggleAll)

var handleChange = R.pipe(
    R.path([
            'target',
            'value'
        ]), 
    app.stateSet('title'))

var render = function () {
    return console.log('render'), 
    ReactDOM.render(
        Main(
            app.stateGet('todos')), 
        document.getElementById('root'))
}

flyd.on(render, app.state)

})()